# #.github-ci.yml


# # .github/workflows/deploy.yml
# name: Deploy to Linux Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       run: echo ${{ secrets.DOCKERHUB_TOKEN_CRM }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME_CRM }} --password-stdin
   
#     - name: Build and Push Docker image
#       run: |
#         docker build -t ${{ secrets.REGISTRY_CRM }}/${{ secrets.DOCKER_IMAGE_CRM }}:latest .
#         docker push ${{ secrets.REGISTRY_CRM }}/${{ secrets.DOCKER_IMAGE_CRM }}:latest

#     - name: SSH into the server and pull the latest Docker image
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_IP }}
#         username: ${{ secrets.SSH_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
#           docker login -u ${{ secrets.DOCKERHUB_USERNAME_CRM }} -p ${{ secrets.DOCKERHUB_TOKEN_CRM }}
#           docker pull ${{ secrets.REGISTRY_CRM }}/${{ secrets.DOCKER_IMAGE_CRM }}:latest
#           docker stop ${{ secrets.DOCKER_IMAGE_CRM }} || true
#           docker rm ${{ secrets.DOCKER_IMAGE_CRM }} || true
#           docker run -d --name ${{ secrets.DOCKER_IMAGE_CRM }} -p 80:3000 \
#             -e REACT_APP_API_URL_ROOT="${{ secrets.REACT_APP_API_URL_ROOT }}" \
#             -e SKIP_PREFLIGHT_CHECK="${{ secrets.SKIP_PREFLIGHT_CHECK }}" \
#             -e REACT_APP_BASENAME="${{ secrets.REACT_APP_BASENAME }}" \
#             -e REACT_APP_API_KEY="${{ secrets.REACT_APP_API_KEY }}" \
#             -e REACT_APP_AUTH_DOMAIN="${{ secrets.REACT_APP_AUTH_DOMAIN }}" \
#             -e REACT_APP_PROJECT_ID="${{ secrets.REACT_APP_PROJECT_ID }}" \
#             -e REACT_APP_STORAGE_BUCKET="${{ secrets.REACT_APP_STORAGE_BUCKET }}" \
#             -e REACT_APP_MESSAGING_SENDER_ID="${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}" \
#             -e REACT_APP_APP_ID="${{ secrets.REACT_APP_APP_ID }}" \
#             -e REACT_APP_MEASUREMENT_ID="${{ secrets.REACT_APP_MEASUREMENT_ID }}" \
#             -e REACT_APP_SITE_KEY="${{ secrets.REACT_APP_SITE_KEY }}" \
#             -e REACT_APP_EMAIL_FIREBASE="${{ secrets.REACT_APP_EMAIL_FIREBASE }}" \
#             -e REACT_APP_PASSWORD_FIREBASE="${{ secrets.REACT_APP_PASSWORD_FIREBASE }}" \
#             -e NODE_OPTIONS="${{ secrets.NODE_OPTIONS }}" \
#             -e REACT_NODE_OPTIONS="${{ secrets.REACT_NODE_OPTIONS }}" \
#             ${{ secrets.REGISTRY_CRM }}/${{ secrets.DOCKER_IMAGE_CRM }}:latest
